name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  fmt:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.canary }} # Continue in case the canary run does not succeed
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        deno-version: [v2.x]
        canary: [false]
        include:
          - deno-version: canary
            os: ubuntu-latest
            canary: true

    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v2

      - name: Test
        run: deno test --doc --allow-all --coverage=cov/

      - name: Coverage
        if: matrix.os == 'ubuntu-latest'
        run: deno coverage --lcov cov/ > cov.lcov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cov.lcov

  bench:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.canary }} # Continue in case the canary run does not succeed
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        deno-version: [v2.x]
        canary: [false]
        include:
          - deno-version: canary
            os: ubuntu-latest
            canary: true

    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v2

      - name: Benchmark
        run: deno bench
